### ISSUE TITLE
11|Session SoapFault trying to authenticate

### ISSUE THREAD

**Issue by zhaonan0218** [amabnl/amadeus-ws-client#154]
Hi Dieter,

I was trying to use the client to make a PNR retrieve request, but received error message: Amadeus\Client\Result Object ( [status] => FATAL [messages] => Array ( [0] => Amadeus\Client\Result\NotOk Object ( [code] => 11 [text] => [level] => Session ) ) [response] => [responseXml] => soap:Client 11|Session| )

I checked the log and pasted below, I suspect the reason was the version of the client, could you take  a look for me please? thank you!
[2018-03-09 21:34:07] RequestResponseLogs.INFO: Called PNR_Retrieve with request: <?xml version="1.0" encoding="UTF-8"?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/PNRRET_15_1_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-secext-1.0.xsd" xmlns:ns4="http://xml.amadeus.com/2010/06/Security_v1"><SOAP-ENV:Header><ns2:MessageID>67FD7569-1766-F71A-9042-6E919A1EA972</ns2:MessageID><ns2:Action>http://webservices.amadeus.com/PNRRET_15_1_1A</ns2:Action><ns2:To>https://nodeA1.test.webservices.amadeus.com/1ASIWSAMNH</ns2:To><oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"> 	<oas:UsernameToken xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" oas1:Id="UsernameToken-1"> 		<oas:Username>SAMROBOT</oas:Username> 		<oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">cdhwnmdDooR6CyiSolT3Jg==</oas:Nonce> 		<oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">Q7SmAIi3N4S05CYqtWnwfv0Y6GE=</oas:Password> 		<oas1:Created>2018-03-09T20:34:07:119Z</oas1:Created> 	</oas:UsernameToken> </oas:Security><ns4:AMA_SecurityHostedUser><ns4:UserID POS_Type="1" PseudoCityCode="SFONH08AA" AgentDutyCode="SU" RequestorType="U"/></ns4:AMA_SecurityHostedUser></SOAP-ENV:Header><SOAP-ENV:Body><ns1:PNR_Retrieve><ns1:retrievalFacts><ns1:retrieve><ns1:type>2</ns1:type></ns1:retrieve><ns1:reservationOrProfileIdentifier><ns1:reservation><ns1:controlNumber>RMBT66</ns1:controlNumber></ns1:reservation></ns1:reservationOrProfileIdentifier></ns1:retrievalFacts></ns1:PNR_Retrieve></SOAP-ENV:Body></SOAP-ENV:Envelope>  [] []
[2018-03-09 21:34:07] RequestResponseLogs.INFO: Response:  <?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing"><soap:Header><wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To><wsa:From><wsa:Address>https://nodeA1.test.webservices.amadeus.com/1ASIWSAMNH</wsa:Address></wsa:From><wsa:Action>http://webservices.amadeus.com/PNRRET_15_1_1A</wsa:Action><wsa:MessageID>urn:uuid:b79fc2a0-31a2-97b4-6932-618a5519b17a</wsa:MessageID><wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">67FD7569-1766-F71A-9042-6E919A1EA972</wsa:RelatesTo><awsse:Session TransactionStatusCode="End"><awsse:SessionId>00CP503NTC</awsse:SessionId><awsse:SequenceNumber>1</awsse:SequenceNumber><awsse:SecurityToken>383YTZIBNMSO61LD8PC7ETLJBB</awsse:SecurityToken></awsse:Session></soap:Header><soap:Body>**<soap:Fault><faultcode>soap:Client</faultcode><faultstring> 11|Session|</faultstring></soap:Fault>**</soap:Body></soap:Envelope> [] []

**Comment by DerMika** [comment]
Usually this is because you use incorrect authentication parameters. Are you sure you properly base_64 encoded the password?

**Comment by zhaonan0218** [comment]
Thank you for your prompt response. And yes, I used base64 password. I have a project xml file and the request format looked a little different than the one in log file, for example the PNR retrieve request looked something like this, I'm not sure if this is the issue:

<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/" xmlns:amasec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:typ="http://xml.amadeus.com/2010/06/Types_v1" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
   <SOAP:Header>
      <wsa:MessageID>f4c46b1e-818b-b03-2b70-f9c2e67aafde</wsa:MessageID>
      <wsa:To>https://nodeA1.test.webservices.amadeus.com/1ASIWSAMNH</wsa:To>
      <wsa:Action>http://webservices.amadeus.com/PNRADD_15_1_1A</wsa:Action>
      <awsse:Session TransactionStatusCode="Start"/>
      <wsse:Security>
         <wsse:UsernameToken>
            <wsse:Username>SAMROBOT</wsse:Username>
            <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">${WS-Security#Password}</wsse:Password>
            <wsse:Nonce>${WS-Security#Nonce}</wsse:Nonce>
            <wsu:Created>${WS-Security#Created}</wsu:Created>
         </wsse:UsernameToken>
      </wsse:Security>
      <amasec:AMA_SecurityHostedUser>
         <amasec:UserID AgentDutyCode="GS" POS_Type="1" PseudoCityCode="SFONH08AA" RequestorType="U"/>
      </amasec:AMA_SecurityHostedUser>
   </SOAP:Header>
   <SOAP:Body>
      <PNR_Retrieve>
         <retrievalFacts>
            <retrieve>
               <type>2</type>
            </retrieve>
            <reservationOrProfileIdentifier>
               <reservation>
                  <controlNumber>RMBT66</controlNumber>
               </reservation>
            </reservationOrProfileIdentifier>
         </retrievalFacts>
      </PNR_Retrieve>
   </SOAP:Body>
</SOAP:Envelope>

**Comment by DerMika** [comment]
I'm currently not home so it's a little hard to compare the two on mobile. I'll look more deeply after the weekend.

**Comment by zhaonan0218** [comment]
Thank you very much Dieter, I have attached the requests files.

[generated_request.txt](https://github.com/amabnl/amadeus-ws-client/files/1798535/generated_request.txt)
[original_request.txt](https://github.com/amabnl/amadeus-ws-client/files/1798536/original_request.txt)

**Comment by zhaonan0218** [comment]
Hi Dieter, sorry to bother you. But did you get a chance to take a look at the request and error message we had? Thank you.

**Comment by DerMika** [comment]
To be clear, generated_request is what this library generates? 

Because there seems to be an error in original_request where it uses the PNRADD action to call a PNR Retrieve message, which would never work anyway.

For the rest, I can't see any problems in the authentication headers in the generated_request.

So what exactly is the problem you're experiencing now, is it still error "soap:Client 11|Session"?

You may want to get in touch with Amadeus Support and have them investigate what's going wrong.

**Comment by zhaonan0218** [comment]
Thank you for your reply Dieter, yes generated_request is the one that this library generated.
Here is the complete error log, what would you recommendations?

[2018-03-09 22:11:46] RequestResponseLogs.INFO: Amadeus\Client\Session\Handler\Base::__construct(): Logger started. [] []
[2018-03-09 22:11:47] RequestResponseLogs.ERROR: SOAPFAULT while sending message PNR_Retrieve:  11|Session| code: 0 at /Applications/MAMP/htdocs/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php line 194:  #0 /Applications/MAMP/htdocs/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(194): SoapClient->__call('PNR_Retrieve', Array) #1 /Applications/MAMP/htdocs/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(1149): Amadeus\Client\Session\Handler\Base->sendMessage('PNR_Retrieve', Object(Amadeus\Client\Struct\Pnr\Retrieve), Array) #2 /Applications/MAMP/htdocs/amadeus/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(225): Amadeus\Client->callMessage('PNR_Retrieve', Object(Amadeus\Client\RequestOptions\PnrRetrieveOptions), Array) #3 /Applications/MAMP/htdocs/amadeus/test.php(81): Amadeus\Client->pnrRetrieve(Object(Amadeus\Client\RequestOptions\PnrRetrieveOptions)) #4 {main} [] []
[2018-03-09 22:11:47] RequestResponseLogs.INFO: Called PNR_Retrieve with request: <?xml version="1.0" encoding="UTF-8"?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://xml.amadeus.com/PNRRET_15_1_1A" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns3="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wsswssecurity-secext-1.0.xsd" xmlns:ns4="http://xml.amadeus.com/2010/06/Security_v1"><SOAP-ENV:Header><ns2:MessageID>2195F644-1B69-DCC1-4AD1-97E111D2094E</ns2:MessageID><ns2:Action>http://webservices.amadeus.com/PNRRET_15_1_1A</ns2:Action><ns2:To>https://nodeA1.test.webservices.amadeus.com/1ASIWSAMNH</ns2:To><oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"> 	<oas:UsernameToken xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" oas1:Id="UsernameToken-1"> 		<oas:Username>SAMROBOT</oas:Username> 		<oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">AZv9fYwMMPr3iAZ44/dJXA==</oas:Nonce> 		<oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">LyAgKFhlJBmzO/F9HZVcirj99ME=</oas:Password> 		<oas1:Created>2018-03-09T21:11:46:972Z</oas1:Created> 	</oas:UsernameToken> </oas:Security><ns4:AMA_SecurityHostedUser><ns4:UserID POS_Type="1" PseudoCityCode="SFONH08AA" AgentDutyCode="SU" RequestorType="U"/></ns4:AMA_SecurityHostedUser></SOAP-ENV:Header><SOAP-ENV:Body><ns1:PNR_Retrieve><ns1:retrievalFacts><ns1:retrieve><ns1:type>2</ns1:type></ns1:retrieve><ns1:reservationOrProfileIdentifier><ns1:reservation><ns1:controlNumber>RMBT66</ns1:controlNumber></ns1:reservation></ns1:reservationOrProfileIdentifier></ns1:retrievalFacts></ns1:PNR_Retrieve></SOAP-ENV:Body></SOAP-ENV:Envelope>  [] []
[2018-03-09 22:11:47] RequestResponseLogs.INFO: Response:  <?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing"><soap:Header><wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To><wsa:From><wsa:Address>https://nodeA1.test.webservices.amadeus.com/1ASIWSAMNH</wsa:Address></wsa:From><wsa:Action>http://webservices.amadeus.com/PNRRET_15_1_1A</wsa:Action><wsa:MessageID>urn:uuid:fb8e8064-dc52-9544-5df1-79b565b3b826</wsa:MessageID><wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">2195F644-1B69-DCC1-4AD1-97E111D2094E</wsa:RelatesTo><awsse:Session TransactionStatusCode="End"><awsse:SessionId>01RNLKNOA5</awsse:SessionId><awsse:SequenceNumber>1</awsse:SequenceNumber><awsse:SecurityToken>1BR48O5EKLTGA20INY6CFEIT42</awsse:SecurityToken></awsse:Session></soap:Header><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring> 11|Session|</faultstring></soap:Fault></soap:Body></soap:Envelope> [] []

**Comment by DerMika** [comment]
Since you usually get `11|Session` errors when using incorrect authentication parameters, you should definitely doublecheck your password.

Important to note is that you sometimes receive the password from Amadeus already in a base64_encoded format. So make sure you're not double-encoding the password!

And if that doesn't fix it, you should contact Amadeus support and have them investigate.

**Comment by zhaonan0218** [comment]
I double checked with Amadeus, and the password should be good, but I did one more test using the original_request, and here is the response, which confirmed that the password is fine, maybe I could send you a private message with the information I have?

<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:wsa="http://www.w3.org/2005/08/addressing">
   <SOAP:Header>
      <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
      <wsa:From>
         <wsa:Address>https://nodeA1.test.webservices.amadeus.com/1ASIWSAMNH</wsa:Address>
      </wsa:From>
      <wsa:Action>http://webservices.amadeus.com/PNRRET_15_1_1A</wsa:Action>
      <wsa:MessageID>urn:uuid:6d6137bb-dd02-e994-318d-8da0e2aa5d76</wsa:MessageID>
      <wsa:RelatesTo RelationshipType="http://www.w3.org/2005/08/addressing/reply">f4c46b1e-818b-b03-2b70-f9c2e67aafde</wsa:RelatesTo>
      <awsse:Session TransactionStatusCode="InSeries">
         <awsse:SessionId>00EALRZY5I</awsse:SessionId>
         <awsse:SequenceNumber>1</awsse:SequenceNumber>
         <awsse:SecurityToken>3TKW3HBZWQEMN2XMWV56UB7C4Z</awsse:SecurityToken>
      </awsse:Session>
   </SOAP:Header>
   <SOAP:Body>
      <soap:Fault xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
         <faultcode>soap:Server</faultcode>
         <faultstring>1931|Application|NO MATCH FOR RECORD LOCATOR</faultstring>
         <faultactor>SI:Backend</faultactor>
      </soap:Fault>
   </SOAP:Body>
</SOAP:Envelope>

**Comment by DerMika** [comment]
Well, the error you're getting now means that the system was unable to find the PNR you requested.

It also means you were successfully authenticated!

**Comment by zhaonan0218** [comment]
Great, but that was the response I get using SOAP UI with the WSDL file we have, but the error message from the library was still soap:Client 11|Session|. That is the issue we are having now.

We actually sent you an email of proposal couple days ago regarding to a project of us, maybe you will be interested. It sent on March 9th to dieter@dermika.be, please let me know your thoughts. thank you!

**Comment by DerMika** [comment]
Ah right. 

So which application are you using to test your password? And how does that handle your Amadeus password? 

Because this library does a base64_decode of the provided password before it sends it to Amadeus (see https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/Session/Handler/SoapHeader4.php#L221). 

This library works for many people, so I really can't think of anything that could be specific to your situation, except for providing the wrong authentication details. So if you're still getting the `11|Session` error, the only course of action I can recommend is you contact Amadeus Support, have them look up the trace logs for your authentication attempts, and let them investigate what's going wrong.

**Comment by DerMika** [comment]
Wait, I think I just found it.

You're using a custom DutyCode:

`<amasec:UserID AgentDutyCode="GS" POS_Type="1" PseudoCityCode="SFONH08AA" RequestorType="U"/>`

So, are you specifying the `'dutyCode' => "GS",` in the 'authParams'?

There is an example shown in the SoapHeader 2 authentication example here in the docs: https://github.com/amabnl/amadeus-ws-client/blob/master/docs/about-get-started.rst#set-up-a-test-client

**Comment by DerMika** [comment]
As we discussed, it seems like the password you were using was the cleartext password after all. Should be fixed by putting a `base64_encode()` around the cleartext password.

Can you confirm that fixes the problem?

**Comment by DerMika** [comment]
Assuming problem was fixed. You can re-open the issue if that wasn't the case after all.

**Comment by quangminht** [comment]
@DerMika I read this issue! I think you should update document (you specifying the 'dutyCode' => "GS", in the 'authParams')
![image](https://user-images.githubusercontent.com/18276304/49796211-a7e78d00-fd6e-11e8-89e8-8aaf0ef4b9ce.png)

Thanks you very much! This topic really help me!

**Comment by haiderg** [comment]
Hi DerMika,

We are facing the same error message "11|Session". In our case it is strange because the same code is working fine on all of our developers system and on one of our server. But it is throwing the exception with message "11|Session" on the server where we have IIS and all of our web sites hosted. 

Can you please help me in this issue as I worked hard to fix it but no success. 

Thanks in advance!!!

**Comment by humanyu** [comment]
How to create nonce and hashpassword for amadeus soap APIs in php. please help me out

**Comment by konorws** [comment]
> Can you please help me in this issue as I worked hard to fix it but no success.
> 
> Thanks in advance!!!

Did you manage to solve your problem? I have exactly the same situation. Locally, everything works but on the server returns error code 11

**Comment by hiteshagja** [comment]
Getting same error 

```
<soap:Body>
      <soap:Fault>
         <faultcode>soap:Client</faultcode>
         <faultstring>11|Session|</faultstring>
      </soap:Fault>
   </soap:Body>
```

For nounce I am generating alphabetic 8 char long, base64 encoded.
I tried Clear text password directly and base64 encoded.

But getting same error as mentioned. 

Help!!

**Comment by haiderg** [comment]
For this issue we contacted with Amadeus but could not fix this issue and at last we have to change our hosting server. Please try some solutions I mentioned our case because we spent one week to fix this issue but no solution.
