### ISSUE TITLE
Fare_InformativePricingWithoutPNR versions < 13 are not yet implemented

### ISSUE THREAD

**Issue by yuriyfroloff** [amabnl/amadeus-ws-client#345]
Hi,

I'm trying to use Fare_InformativePricingWithoutPNR and do this:

```php
<?php

require 'vendor/autoload.php';

use Monolog\Logger;
use Monolog\Handler\StreamHandler;

$msgLog = new Logger('RequestResponseLogs');
$msgLog->pushHandler(new StreamHandler('logs/requestresponse.log', Logger::INFO));

use Amadeus\Client;
use Amadeus\Client\Params;
use Amadeus\Client\Result;
use Amadeus\Client\RequestOptions\FareInformativePricingWithoutPnrOptions;
use Amadeus\Client\RequestOptions\Fare\InformativePricing\Passenger;
use Amadeus\Client\RequestOptions\Fare\InformativePricing\Segment;


$params = new Params([
    'authParams'           => [
        'officeId'     => '********', //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
        'userId'       => '********', //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
        'passwordData' => '********' // **base 64 encoded** password
    ],
    'sessionHandlerParams' => [
        'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
        'wsdl'              => 'wsdl_test/********_PDT_20190702_111048.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
        'stateful'          => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
        'logger'            => $msgLog
    ],
    'requestCreatorParams' => [
        'receivedFrom' => 'YFTEST' // The "Received From" string that will be visible in PNR History
    ]
]);

$client = new Client($params);

$informativePricingResponse = $client->fareInformativePricingWithoutPnr(
    new FareInformativePricingWithoutPnrOptions([
        'passengers' => [
            new Passenger([
                'tattoos' => [1, 2],
                'type' => Passenger::TYPE_ADULT
            ])
        ],
        'segments' => [
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2019-09-01 15:30:00'),
                'from' => 'BRU',
                'to' => 'LIS',
                'marketingCompany' => 'TP',
                'flightNumber' => '643',
                'bookingClass' => 'Y',
                'segmentTattoo' => 1,
                'groupNumber' => 1
            ]),
            new Segment([
                'departureDate' => \DateTime::createFromFormat('Y-m-d H:i:s', '2019-09-10 16:00:00'),
                'from' => 'LIS',
                'to' => 'BRU',
                'marketingCompany' => 'TP',
                'flightNumber' => '644',
                'bookingClass' => 'C',
                'segmentTattoo' => 2,
                'groupNumber' => 2
            ])
        ]
    ])
);

?>
```
As a result I get an error:

```php
<br />
<b>Fatal error</b>:  Uncaught Amadeus\Client\RequestCreator\MessageVersionUnsupportedException: Fare_InformativePricingWithoutPNR versions &lt; 13 are not yet implemented in D:\OSPanel\domains\tk\amadeus\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\Struct\Fare\InformativePricingWithoutPNR12.php:45
Stack trace:
#0 D:\OSPanel\domains\tk\amadeus\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\RequestCreator\Converter\Fare\InformativePricingWithoutPNRConv.php(45): Amadeus\Client\Struct\Fare\InformativePricingWithoutPNR12-&gt;__construct(Object(Amadeus\Client\RequestOptions\FareInformativePricingWithoutPnrOptions))
#1 D:\OSPanel\domains\tk\amadeus\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\RequestCreator\Base.php(93): Amadeus\Client\RequestCreator\Converter\Fare\InformativePricingWithoutPNRConv-&gt;convert(Object(Amadeus\Client\RequestOptions\FareInformativePricingWithoutPnrOptions), '8.1')
#2 D:\OSPanel\domains\tk\amadeus\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client.php(1532): Amadeus\Client\RequestCreator\Base-&gt;createR in <b>D:\OSPanel\domains\tk\amadeus\vendor\amabnl\amadeus-ws-client\src\Amadeus\Client\Struct\Fare\InformativePricingWithoutPNR12.php</b> on line <b>45</b><br />
```
I use amadeus-ws-client v. 1.7, php 7.2.0. Other services which I tested work well.

Please help, thanks in advance.

**Comment by DerMika** [comment]
Is this a WSDL for a recently created WSAP? For a new application, or migrating from an older application?

I'm asking because I don't really have the time to implement old versions of `Fare_InformativePricingWithoutPNR`  right now, so if you could upgrade your WSAP to a newer version, that would solve your problem :)

**Comment by yuriyfroloff** [comment]
Thanks for the quick response.

Yesterday, our account manager from Amadeus added service to our WSAP for test environment. Today I followed the link https://developers.amadeus.com/my-enterprise-ws/soap?page=1&count=50&sorting=name,asc and downloaded new WSDL with selection "PDT" and "Soap header 4.0". Then I used the downloaded WSDL in my script and got this error. Now I tried to re-download WSDL and use it, but no changes.

Could you tell me how I can "upgrade WSAP" actually and use the new version of the service? I don’t need the old one.

Thanks a lot!

**Comment by DerMika** [comment]
You should ask your account manager to upgrade the version of the service in your WSDL

**Comment by DerMika** [comment]
Oh and another thing to check:if there are multiple versions of this message in your WSDL, you can delete the old versions. This will require some manual WSDL editing

**Comment by yuriyfroloff** [comment]
In my WSDL I found only "Fare_InformativePricingWithoutPNR_08_1_1A.xsd". That means that verion is 8? What version should I ask for?

**Comment by DerMika** [comment]
Version 13 or higher :)

**Comment by yuriyfroloff** [comment]
I asked our account manager to update the version.
After update I downloaded the new PDT WSDL and now everything works fine.
Thanks!
