### ISSUE TITLE
Error recognizing message versions in Request Creator

### ISSUE THREAD

**Issue by bimusiek** [amabnl/amadeus-ws-client#71]
Hey, I just updated the lib to newest `master` and when doing pricing I am getting
```
[SOAP-ERROR: Encoding: object has no 'pricingOptionGroup' property] 
```
My code:
```php
private function pricePnr($currency) {
        $options =  [
            'ticketType' => FarePricePnrWithBookingClassOptions::TICKET_TYPE_ELECTRONIC,
            'currencyOverride' => $currency
        ];
        $pricingResponse = $this->client->farePricePnrWithBookingClass(
            new FarePricePnrWithBookingClassOptions($options)
        );
        return $pricingResponse;
    }
```

And error:
```
SOAPFAULT while sending message Fare_PricePNRWithBookingClass: SOAP-ERROR: Encoding: object has no 'pricingOptionGroup' property code: 0 at /var/www/html/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php line 194:  
#0 /var/www/html/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php(194): SoapClient->__call('Fare_PricePNRWi...', Array) 
#1 /var/www/html/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(1072): Amadeus\Client\Session\Handler\Base->sendMessage('Fare_PricePNRWi...', Object(Amadeus\Client\Struct\Fare\PricePNRWithBookingClass12), Array) 
#2 /var/www/html/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client.php(508): Amadeus\Client->callMessage('Fare_PricePNRWi...', Object(Amadeus\Client\RequestOptions\FarePricePnrWithBookingClassOptions), Array) 
#3 /var/www/html/amadeus/apps/booking/manager.php(177): Amadeus\Client->farePricePnrWithBookingClass(Object(Amadeus\Client\RequestOptions\FarePricePnrWithBookingClassOptions)) 
```
I have 14.1 version of this endpoint but I see lib is using version 12? 
Any ideas what is wrong? I tried to look in the code but did not find anything that can cause this issue.

**Comment by DerMika** [comment]
Well, I did fix [a bug](https://github.com/amabnl/amadeus-ws-client/issues/57) recently that may have changed the way the Pricing messages are being constructed. 

Could you step through the code and see if `Amadeus\Client\RequestCreator\Converter\Fare\PricePNRWithBookingClassConv` creates a PricePNRWithBookingClass12 or a PricePNRWithBookingClass13 message, and if this is consistent with the version in your WSDL?

**Comment by bimusiek** [comment]
Lib is using `PricePNRWithBookingClass12` however the version I have is `14.1.1`

**Comment by DerMika** [comment]
well shit.

**Comment by DerMika** [comment]
What PHP version are you running? And what OS?

**Comment by bimusiek** [comment]
It is dockerized container `php:fpm`. It uses `debian:jessie` and `php 7.1`.

**Comment by bimusiek** [comment]
How do you recognise version in the lib? I think the code change should not break it as I checked:
```
php > var_dump(floatval('14.1.1') < floatval(13));
php shell code:1:
bool(false)
php > var_dump('14.1.1' < 13);
php shell code:1:
bool(false)
php > var_dump('14.1.1A' < 13);
php shell code:1:
bool(false)
php > var_dump(floatval('14.1.1A') < floatval(13));
php shell code:1:
bool(false)
php > var_dump(floatval('14_1_1A') < floatval(13));
php shell code:1:
bool(false)
php > var_dump('14_1_1A' < 13);
php shell code:1:
bool(false)
```

**Comment by DerMika** [comment]
That's done in the WsdlAnalyzer, which checks which messages and versions of messages are defined in the WSDL you've provided.

**Comment by DerMika** [comment]
You don't happen to have multiple versions of this message in your WSDL?

**Comment by bimusiek** [comment]
No, just this one.
```
      <xs:import namespace="http://xml.amadeus.com/TIPNRQ_14_1_1A" schemaLocation="Fare_InformativePricingWithoutPNR_14_1_1A.xsd" />
      <xs:import namespace="http://xml.amadeus.com/TIPNRR_14_1_1A" schemaLocation="Fare_InformativePricingWithoutPNRReply_14_1_1A.xsd" />
```

**Comment by bimusiek** [comment]
This is quite weird, it should still work:
```
php > $fullVersionString = "Fare_InformativePricingWithoutPNR_14_1_1A";
php > $marker = strpos($fullVersionString, '_', strpos($fullVersionString, '_') + 1);
php >         $num = substr($fullVersionString, $marker + 1);
php > var_dump($num);
php shell code:1:
string(7) "14_1_1A"
php > var_dump(str_replace('_', '.', $num));
php shell code:1:
string(7) "14.1.1A"
php > var_dump(floatval('14.1.1A') < floatval(13));
php shell code:1:
bool(false)
```

**Comment by DerMika** [comment]
Can you add the following line to `Amadeus\Client\Session\Handler\Base` after line 321 and let me know the contents of the var_dump?

`var_dump($this->messagesAndVersions); die();`

**Comment by bimusiek** [comment]
```
/var/www/html/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/Session/Handler/Base.php:322:
array (size=39)
  'Air_FlightInfo' => 
    array (size=2)
      'version' => string '7.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Air_RebookAirSegment' => 
    array (size=2)
      'version' => string '3.2' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Air_SellFromRecommendation' => 
    array (size=2)
      'version' => string '5.2' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Command_Cryptic' => 
    array (size=2)
      'version' => string '7.3' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'DocIssuance_IssueCombined' => 
    array (size=2)
      'version' => string '15.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'DocIssuance_IssueMiscellaneousDocuments' => 
    array (size=2)
      'version' => string '15.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'DocIssuance_IssueTicket' => 
    array (size=2)
      'version' => string '15.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'DocRefund_InitRefund' => 
    array (size=2)
      'version' => string '13.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'DocRefund_ProcessRefund' => 
    array (size=2)
      'version' => string '13.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'DocRefund_UpdateRefund' => 
    array (size=2)
      'version' => string '13.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'FOP_CreateFormOfPayment' => 
    array (size=2)
      'version' => string '14.6' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Fare_CheckRules' => 
    array (size=2)
      'version' => string '7.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Fare_ConvertCurrency' => 
    array (size=2)
      'version' => string '8.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Fare_InformativePricingWithoutPNR' => 
    array (size=2)
      'version' => string '14.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Fare_MasterPricerTravelBoardSearch' => 
    array (size=2)
      'version' => string '14.3' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Fare_PricePNRWithBookingClass' => 
    array (size=2)
      'version' => string '14.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'MiniRule_GetFromETicket' => 
    array (size=2)
      'version' => string '13.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'MiniRule_GetFromPricing' => 
    array (size=2)
      'version' => string '11.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'MiniRule_GetFromPricingRec' => 
    array (size=2)
      'version' => string '11.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'PNR_AddMultiElements' => 
    array (size=2)
      'version' => string '14.2' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'PNR_Cancel' => 
    array (size=2)
      'version' => string '14.2' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'PNR_Retrieve' => 
    array (size=2)
      'version' => string '14.2' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'PNR_Search' => 
    array (size=2)
      'version' => string '15.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Queue_PlacePNR' => 
    array (size=2)
      'version' => string '3.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Security_Authenticate' => 
    array (size=2)
      'version' => string '6.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Security_SignOut' => 
    array (size=2)
      'version' => string '4.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Service_IntegratedPricing' => 
    array (size=2)
      'version' => string '15.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Service_StandaloneCatalogue' => 
    array (size=2)
      'version' => string '16.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_ATCShopperMasterPricerTravelBoardSearch' => 
    array (size=2)
      'version' => string '13.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_CancelDocument' => 
    array (size=2)
      'version' => string '11.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_CheckEligibility' => 
    array (size=2)
      'version' => string '13.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_CreateTSMFareElement' => 
    array (size=2)
      'version' => string '10.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_CreateTSMFromPricing' => 
    array (size=2)
      'version' => string '9.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_CreateTSTFromPricing' => 
    array (size=2)
      'version' => string '4.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_DisplayTSMP' => 
    array (size=2)
      'version' => string '13.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_DisplayTST' => 
    array (size=2)
      'version' => string '15.1' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_ProcessETicket' => 
    array (size=2)
      'version' => string '4.1' (length=3)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_ReissueConfirmedPricing' => 
    array (size=2)
      'version' => string '13.2' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
  'Ticket_RepricePNRWithBookingClass' => 
    array (size=2)
      'version' => string '14.3' (length=4)
      'wsdl' => string 'dc22e4ee' (length=8)
```

**Comment by bimusiek** [comment]
While printing directly in `Conv`:
```php
var_dump($version);
var_dump(floatval($version) < floatval(13));
```

```php
/var/www/html/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/RequestCreator/Converter/Fare/PricePNRWithBookingClassConv.php:44:
array (size=2)
  'version' => string '14.1' (length=4)
  'wsdl' => string 'dc22e4ee' (length=8)
/var/www/html/vendor/amabnl/amadeus-ws-client/src/Amadeus/Client/RequestCreator/Converter/Fare/PricePNRWithBookingClassConv.php:45:boolean true
```

**Comment by DerMika** [comment]
Wait, are you getting an array as $version???

**Comment by DerMika** [comment]
Ok, that sounds like a dumb mistake on my part :)

**Comment by bimusiek** [comment]
Yes :( 

Changing it to `if (floatval($version['version']) < floatval(13)) {` helped but I guess it should not get array here.

**Comment by DerMika** [comment]
Ok, It'll be fixed tonight, but it'll require some work on the unittests. Hang in there - and thanks for finding this bug!

**Comment by bimusiek** [comment]
Thanks for help. I am in no hurry as I just patched it directly in container so I can work with this patch for now.

**Comment by DerMika** [comment]
This should be fixed now. Please test! :)

**Comment by bimusiek** [comment]
Works ❤️  Thanks!
